export const UserDef = {
    key: "user",
    primaryKey: "userId",
    tableEng: "User",
    tableName: "유저",
    allColumns: {
        columns: {
            userId: "유저아이디",
            email: "이메일",
            password: "비밀번호",
            nickname: "닉네임",
            role: "역할",
            offerings: "수업내역",
            enrollments: "수강내역",
            comments: "댓글내역",
            posts: "게시글내역",
            notices: "공지내역",
        },
        createColumns: {
            userId: "유저아이디",
            email: "이메일",
            password: "비밀번호",
            nickname: "닉네임",
            role: "역할",
            offerings: "수업내역",
            enrollments: "수강내역",
            comments: "댓글내역",
            posts: "게시글내역",
            notices: "공지내역",
        },
        responseColumns: {
            userId: "유저아이디",
            email: "이메일",
            password: "비밀번호",
            nickname: "닉네임",
            role: "역할",
            offerings: "수업내역",
            enrollments: "수강내역",
            comments: "댓글내역",
            posts: "게시글내역",
            notices: "공지내역",
        },
        updateColumns: {
            userId: "유저아이디",
            email: "이메일",
            password: "비밀번호",
            nickname: "닉네임",
            role: "역할",
            offerings: "수업내역",
            enrollments: "수강내역",
            comments: "댓글내역",
            posts: "게시글내역",
            notices: "공지내역",
        },
    },

    excludeList: ["offerings", "enrollments", "comments", "posts", "notices"],
    color: "bg-teal-100",
}