export const tableDefinitions = {
    "attendance": {
        key: "attendance",
        primaryKey: "attendanceId",
        tableEng: "Attendance",
        tableName: "출석",
        allColumns: {
            columns: {
                attendanceId: "이름",
                localDateTime: "출석일",
                status: "상태",
                enrollment: "수강내역"
            },
            createColumns: {
                attendanceId: "이름",
                localDateTime: "출석일",
                status: "상태",
                enrollment: "수강내역"
            },
            responseColumns: {
                attendanceId: "이름",
                localDateTime: "출석일",
                status: "상태",
                enrollment: "수강내역"
            },
            updateColumns: {
                attendanceId: "이름",
                localDateTime: "출석일",
                status: "상태",
                enrollment: "수강내역"
            },
        },
        excludeList: ["enrollment"],
        color: "bg-grey-100",
    },
    "board": {
        key: "board",
        primaryKey: "boardId",
        tableEng: "Board",
        tableName: "게시판종류",
        allColumns: {
            columns: {
                boardId: "게시판번호",
                boardName: "게시판종류",
                posts: "게시판글",
            },
            createColumns: {
                boardId: "게시판번호",
                boardName: "게시판종류",
                posts: "게시판글",
            },
            responseColumns: {
                boardId: "게시판번호",
                boardName: "게시판종류",
                posts: "게시판글",
            },
            updateColumns: {
                boardId: "게시판번호",
                boardName: "게시판종류",
                posts: "게시판글",
            },
        },

        excludeList: ["posts"],
        color: "bg-gray-200",
    },
    "comment": {
        key: "comment",
        primaryKey: "commentId",
        tableEng: "Comment",
        tableName: "댓글",
        allColumns: {
            columns: {
                commentId: "댓글아이디",
                content: "댓글내용",
                createdAt: "일자",
                user: "유저",
                posts: "게시판글",
            },
            createColumns: {
                commentId: "댓글아이디",
                content: "댓글내용",
                createdAt: "일자",
                user: "유저",
                posts: "게시판글",
            },
            responseColumns: {
                commentId: "댓글아이디",
                content: "댓글내용",
                createdAt: "일자",
                user: "유저",
                posts: "게시판글",
            },
            updateColumns: {
                commentId: "댓글아이디",
                content: "댓글내용",
                createdAt: "일자",
                user: "유저",
                posts: "게시판글",
            },
        },
        excludeList: ["user", "posts"],
        color: "bg-stone-100",
    },
    "course": {
        key: "course",
        tableEng: "Course",
        tableName: "강의종류",
        primaryKey: "courseId",
        allColumns: {
            columns: {
                courseId: "강의과목코드",
                courseName: "과목명",
                description: "강의설명",
                credits: "학점",
                department: "학과",
                offerings: "하위강의들",
            },
            createColumns: {
                courseId: "강의과목코드",
                courseName: "과목명",
                description: "강의설명",
                credits: "학점",
                department: "학과",
                offerings: "하위강의들",
            },
            responseColumns: {
                courseId: "강의과목코드",
                courseName: "과목명",
                description: "강의설명",
                credits: "학점",
                department: "학과",
                offerings: "하위강의들",
            },
            updateColumns: {
                courseId: "강의과목코드",
                courseName: "과목명",
                description: "강의설명",
                credits: "학점",
                department: "학과",
                offerings: "하위강의들",
            },
        },

        excludeList: ["department", "offerings"],
        color: "bg-neutral-200",
    },
    "courseOffering": {
        key: "offeringId",
        primaryKey: "offeringId",
        tableEng: "CourseOffering",
        tableName: "개설강의",
        allColumns: {
            columns: {
                offeringId: "개설강의코드",
                professorName: "교수이림",
                courseName: "강의이름",
                year: "년도",
                semester: "학기",
                course: "강의정보",
                user: "유저",
                enrollments: "수강내역들",
                timeTables: "시간표들",
            },
            createColumns: {
                offeringId: "개설강의코드",
                professorName: "교수이림",
                courseName: "강의이름",
                year: "년도",
                semester: "학기",
                course: "강의정보",
                user: "유저",
                enrollments: "수강내역들",
                timeTables: "시간표들",
            },
            responseColumns: {
                offeringId: "개설강의코드",
                professorName: "교수이림",
                courseName: "강의이름",
                year: "년도",
                semester: "학기",
                course: "강의정보",
                user: "유저",
                enrollments: "수강내역들",
                timeTables: "시간표들",
            },
            updateColumns: {
                offeringId: "개설강의코드",
                professorName: "교수이림",
                courseName: "강의이름",
                year: "년도",
                semester: "학기",
                course: "강의정보",
                user: "유저",
                enrollments: "수강내역들",
                timeTables: "시간표들",
            },
        },
        columns: {

        },

        excludeList: ["course", "user", "enrollments", "timeTables"],
        color: "bg-yellow-100",
    },
    "department": {
        key: "department",
        primaryKey: "departmentId",
        tableEng: "Department",
        tableName: "학과",
        allColumns: {
            columns: {
                departmentId: "학과아이디",
                deptName: "학과이름",
                courses: "코스목록"
            },
            createColumns: {
                departmentId: "학과아이디",
                deptName: "학과이름",
                courses: "코스목록"
            },
            responseColumns: {
                departmentId: "학과아이디",
                deptName: "학과이름",
                courses: "코스목록"
            },
            updateColumns: {
                departmentId: "학과아이디",
                deptName: "학과이름",
                courses: "코스목록"
            },
        },
        excludeList: ["courses"],
        color: "bg-yellow-200",
    },
    "enrollment": {
        key: "enrollment",
        primaryKey: "enrollmentId",
        tableEng: "Enrollment",
        tableName: "수강신청내역",
        allColumns: {
            columns: {
                enrollmentId: "수강 내역 아이디",
                enrollDate: "강의 개설 날짜",
                courseOffering: "강의 정보",
                user: "유저",
                grades: "성적들",
                attendances: "출석들",
                reviews: "리뷰들",
            },
            createColumns: {
                enrollmentId: "수강 내역 아이디",
                enrollDate: "강의 개설 날짜",
                courseOffering: "강의 정보",
                user: "유저",
                grades: "성적들",
                attendances: "출석들",
                reviews: "리뷰들",
            },
            responseColumns: {
                enrollmentId: "수강 내역 아이디",
                enrollDate: "강의 개설 날짜",
                courseOffering: "강의 정보",
                user: "유저",
                grades: "성적들",
                attendances: "출석들",
                reviews: "리뷰들",
            },
            updateColumns: {
                enrollmentId: "수강 내역 아이디",
                enrollDate: "강의 개설 날짜",
                courseOffering: "강의 정보",
                user: "유저",
                grades: "성적들",
                attendances: "출석들",
                reviews: "리뷰들",
            },
        },

        excludeList: ["courseOffering", "user", "grades", "attendances", "reviews"],
        color: "bg-grey-600",
    },
    "grade": {
        key: "grade",
        primaryKey: "gradeId",
        tableEng: "Grade",
        tableName: "성적",
        allColumns: {
            columns: {
                gradeId: "성적아이디",
                gradeValue: "성적값",
                courseName: "강의이름",
                enrollment: "수강내역",
            },
            createColumns: {
                gradeId: "성적아이디",
                gradeValue: "성적값",
                courseName: "강의이름",
                enrollment: "수강내역",
            },
            responseColumns: {
                gradeId: "성적아이디",
                gradeValue: "성적값",
                courseName: "강의이름",
                enrollment: "수강내역",
            },
            updateColumns: {
                gradeId: "성적아이디",
                gradeValue: "성적값",
                courseName: "강의이름",
                enrollment: "수강내역",
            },
        },

        excludeList: ["enrollment", "courseName"],
        color: "bg-amber-100",
    },
    "notice": {
        key: "notice",
        primaryKey: "noticeId",
        tableEng: "Notice",
        tableName: "공지사항",
        allColumns: {
            columns: {
                noticeId: "공지사항아이디",
                title: "제목",
                content: "내용",
                createdAt: "작성일자",
                userDTO: "유저",
            },
            createColumns: {
                noticeId: "공지사항아이디",
                title: "제목",
                content: "내용",
                createdAt: "작성일자",
                userDTO: "유저",
            },
            responseColumns: {
                noticeId: "공지사항아이디",
                title: "제목",
                content: "내용",
                createdAt: "작성일자",
                userDTO: "유저",
            },
            updateColumns: {
                noticeId: "공지사항아이디",
                title: "제목",
                content: "내용",
                createdAt: "작성일자",
                userDTO: "유저",
            },
        },

        excludeList: ["userDTO"],
        color: "bg-amber-100",
    },
    "post": {
        key: "post",
        primaryKey: "postId",
        tableEng: "Post",
        tableName: "게시글",
        allColumns: {
            columns: {
                postId: "게시글아이디",
                title: "제목",
                content: "내용",
                createAt: "작성일자",
                userDTO: "유저",
            },
            createColumns: {
                postId: "게시글아이디",
                title: "제목",
                content: "내용",
                createAt: "작성일자",
                userDTO: "유저",
            },
            responseColumns: {
                postId: "게시글아이디",
                title: "제목",
                content: "내용",
                createAt: "작성일자",
                userDTO: "유저",
            },
            updateColumns: {
                postId: "게시글아이디",
                title: "제목",
                content: "내용",
                createAt: "작성일자",
                userDTO: "유저",
            },
        },

        excludeList: ["userDTO"],
        color: "bg-lime-100",
    },
    "review": {
        key: "review",
        primaryKey: "reviewId",
        tableEng: "Review",
        tableName: "리뷰",
        allColumns: {
            columns: {
                reviewId: "리뷰아이디",
                rating: "평가점수",
                comment: "댓글내용",
                createdAt: "작성일자",
                updatedAt: "수정날짜",
                courseName: "강의이름",
                studentNickname: "학생이름",
            },
            createColumns: {
                reviewId: "리뷰아이디",
                rating: "평가점수",
                comment: "댓글내용",
                createdAt: "작성일자",
                updatedAt: "수정날짜",
                courseName: "강의이름",
                studentNickname: "학생이름",
            },
            responseColumns: {
                reviewId: "리뷰아이디",
                rating: "평가점수",
                comment: "댓글내용",
                createdAt: "작성일자",
                updatedAt: "수정날짜",
                courseName: "강의이름",
                studentNickname: "학생이름",
            },
            updateColumns: {
                reviewId: "리뷰아이디",
                rating: "평가점수",
                comment: "댓글내용",
                createdAt: "작성일자",
                updatedAt: "수정날짜",
                courseName: "강의이름",
                studentNickname: "학생이름",
            },
        },
        excludeList: ["enrollmentDTO"],
        color: "bg-green-100",
    },
    "time": {
        key: "time",
        primaryKey: "timetableId",
        tableEng: "TimeTable",
        tableName: "시간표",
        allColumns: {
            columns: {
                timetableId: "시간표아이디",
                dayOfWeek: "요일",
                startTime: "수업시작시간",
                endTime: "수업종료시간",
                location: "위치",
                courseName: "강의명",
                nickName: "학생이름"
            },
            createColumns: {
                offeringId: "개설강의고유Id",
                dayOfWeek: "요일",
                startTime: "시작시간",
                endTime: "종료시간",
                location: "강의실",
            },
            responseColumns: {
                timetableId: "시간표 아이디",
                dayOfWeek: "요일",
                startTime: "시간시간",
                endTime: "종료시간",
                location: "강의실",
                courseName: "강의명",
                professorNickname: "학생이름",
                offeringId: "개설강의고유Id"
            },
            updateColumns: {
                dayOfWeek: "요일",
                startTime: "시간시간",
                endTime: "종료시간",
                location: "강의실",
            },
        },
        excludeList: ["courseOffering"],
        color: "bg-emerald-100",
    },
    "user": {
        key: "user",
        primaryKey: "userId",
        tableEng: "User",
        tableName: "유저",
        allColumns: {
            columns: {
                userId: "유저아이디",
                email: "이메일",
                password: "비밀번호",
                nickname: "닉네임",
                role: "역할",
                offerings: "수업내역",
                enrollments: "수강내역",
                comments: "댓글내역",
                posts: "게시글내역",
                notices: "공지내역",
            },
            createColumns: {
                userId: "유저아이디",
                email: "이메일",
                password: "비밀번호",
                nickname: "닉네임",
                role: "역할",
                offerings: "수업내역",
                enrollments: "수강내역",
                comments: "댓글내역",
                posts: "게시글내역",
                notices: "공지내역",
            },
            responseColumns: {
                userId: "유저아이디",
                email: "이메일",
                password: "비밀번호",
                nickname: "닉네임",
                role: "역할",
                offerings: "수업내역",
                enrollments: "수강내역",
                comments: "댓글내역",
                posts: "게시글내역",
                notices: "공지내역",
            },
            updateColumns: {
                userId: "유저아이디",
                email: "이메일",
                password: "비밀번호",
                nickname: "닉네임",
                role: "역할",
                offerings: "수업내역",
                enrollments: "수강내역",
                comments: "댓글내역",
                posts: "게시글내역",
                notices: "공지내역",
            },
        },

        excludeList: ["offerings", "enrollments", "comments", "posts", "notices"],
        color: "bg-teal-100",
    },
};