import React from "react";

const TimetablePage = () => {
  return (
    <div className="">
      <table border="3">
        <caption>시간표</caption>
        <thead>
          <tr>
            <th>교시</th>
            <th>월</th>
            <th>화</th>
            <th>수</th>
            <th>목</th>
            <th>금</th>
            <th>토</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <p>01교시</p>
              <p>09:00~09:30</p>
            </td>
            <td>2행2열</td>
            <td>2행3열</td>
            <td>2행4열</td>
            <td>2행5열</td>
            <td>2행6열</td>
            <td>2행7열</td>
          </tr>
          <tr>
            <td>
              <p>02교시</p>
              <p>09:30~10:00</p>
            </td>
            <td>3행2열</td>
            <td>3행3열</td>
            <td>3행4열</td>
            <td>3행5열</td>
            <td>3행6열</td>
            <td>3행7열</td>
          </tr>
          <tr>
            <td>
              <p>03교시</p>
              <p>10:00~10:30</p>
            </td>
            <td>4행2열</td>
            <td>4행3열</td>
            <td>4행4열</td>
            <td>4행5열</td>
            <td>4행6열</td>
            <td>4행7열</td>
          </tr>
          <tr>
            <td>
              <p>04교시</p>
              <p>10:30~11:00</p>
            </td>
            <td>5행2열</td>
            <td>5행3열</td>
            <td>5행4열</td>
            <td>5행5열</td>
            <td>5행6열</td>
            <td>5행7열</td>
          </tr>
          <tr>
            <td>
              <p>05교시</p>
              <p>11:00~11:30</p>
              <td>6행2열</td>
              <td>6행3열</td>
              <td>6행4열</td>
              <td>6행5열</td>
              <td>6행6열</td>
              <td>6행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>06교시</p>
              <p>11:30~12:00</p>
              <td>7행2열</td>
              <td>7행3열</td>
              <td>7행4열</td>
              <td>7행5열</td>
              <td>7행6열</td>
              <td>7행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>07교시</p>
              <p>12:00~12:30</p>
              <td>8행2열</td>
              <td>8행3열</td>
              <td>8행4열</td>
              <td>8행5열</td>
              <td>8행6열</td>
              <td>8행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>08교시</p>
              <p>12:30~13:00</p>
              <td>9행2열</td>
              <td>9행3열</td>
              <td>9행4열</td>
              <td>9행5열</td>
              <td>9행6열</td>
              <td>9행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>09교시</p>
              <p>13:00~13:30</p>
              <td>10행2열</td>
              <td>10행3열</td>
              <td>10행4열</td>
              <td>10행5열</td>
              <td>10행6열</td>
              <td>10행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>10교시</p>
              <p>13:30~14:00</p>
              <td>11행2열</td>
              <td>11행3열</td>
              <td>11행4열</td>
              <td>11행5열</td>
              <td>11행6열</td>
              <td>11행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>11교시</p>
              <p>14:00~14:30</p>
              <td>12행2열</td>
              <td>12행3열</td>
              <td>12행4열</td>
              <td>12행5열</td>
              <td>12행6열</td>
              <td>12행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>12교시</p>
              <p>14:30~15:00</p>
              <td>13행2열</td>
              <td>13행3열</td>
              <td>13행4열</td>
              <td>13행5열</td>
              <td>13행6열</td>
              <td>13행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>13교시</p>
              <p>15:00~15:30</p>
              <td>14행2열</td>
              <td>14행3열</td>
              <td>14행4열</td>
              <td>14행5열</td>
              <td>14행6열</td>
              <td>14행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>14교시</p>
              <p>15:30~16:00</p>
              <td>15행2열</td>
              <td>15행3열</td>
              <td>15행4열</td>
              <td>15행5열</td>
              <td>15행6열</td>
              <td>15행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>15교시</p>
              <p>16:00~16:30</p>
              <td>16행2열</td>
              <td>16행3열</td>
              <td>16행4열</td>
              <td>16행5열</td>
              <td>16행6열</td>
              <td>16행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>16교시</p>
              <p>16:30~17:00</p>
              <td>17행2열</td>
              <td>17행3열</td>
              <td>17행4열</td>
              <td>17행5열</td>
              <td>17행6열</td>
              <td>17행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>17교시</p>
              <p>17:00~17:30</p>
              <td>18행2열</td>
              <td>18행3열</td>
              <td>18행4열</td>
              <td>18행5열</td>
              <td>18행6열</td>
              <td>18행7열</td>
            </td>
          </tr>
          <tr>
            <td>
              <p>18교시</p>
              <p>17:30~18:00</p>
              <td>19행2열</td>
              <td>19행3열</td>
              <td>19행4열</td>
              <td>19행5열</td>
              <td>19행6열</td>
              <td>19행7열</td>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default TimetablePage;
