export const OfferingDef = {
    key: "offering",
    primaryKey: "offeringId",
    tableEng: "CourseOffering",
    tableName: "개설강의",
    allColumns: {
        columns: {
            offeringId: "개설강의코드",
            professorName: "교수이림",
            courseName: "강의이름",
            year: "년도",
            semester: "학기",
            course: "강의정보",
            user: "유저",
            enrollments: "수강내역들",
            timeTables: "시간표들",
        },
        createColumns: {
            offeringId: "개설강의코드",
            professorName: "교수이림",
            courseName: "강의이름",
            year: "년도",
            semester: "학기",
            course: "강의정보",
            user: "유저",
            enrollments: "수강내역들",
            timeTables: "시간표들",
        },
        responseColumns: {
            offeringId: "개설강의코드",
            professorName: "교수이림",
            courseName: "강의이름",
            year: "년도",
            semester: "학기",
            course: "강의정보",
            user: "유저",
            enrollments: "수강내역들",
            timeTables: "시간표들",
        },
        updateColumns: {
            offeringId: "개설강의코드",
            professorName: "교수이림",
            courseName: "강의이름",
            year: "년도",
            semester: "학기",
            course: "강의정보",
            user: "유저",
            enrollments: "수강내역들",
            timeTables: "시간표들",
        },
    },
    columns: {},

    excludeList: ["course", "user", "enrollments", "timeTables"],
    color: "bg-yellow-100",
}