export const TimeTableDef = {
  key: "time",
  primaryKey: "timetableId",
  tableEng: "TimeTable",
  tableName: "시간표",
  allColumns: {
    columns: {
      timetableId: "시간표아이디",
      dayOfWeek: "요일",
      startTime: "수업시작시간",
      endTime: "수업종료시간",
      location: "위치",
      courseName: "강의명",
      nickName: "학생이름",
    },
    createColumns: {
      sectionId: "분반Id",
      dayOfWeek: "요일",
      startTime: "시작시간",
      endTime: "종료시간",
    },
    responseColumns: {
      timetableId: "시간표 아이디",
      dayOfWeek: "요일",
      startTime: "시간시간",
      endTime: "종료시간",
      offeringId: "개설강의고유Id",
      courseName: "강의명",
      professorNickname: "학생이름",
      sectionName: "분반명",
      sectionId: "분반id",
    },
    updateColumns: {
      timetableId: "시간표아이디",
      dayOfWeek: "요일",
      startTime: "시간시간",
      endTime: "종료시간",
    },
  },
  excludeList: ["courseOffering"],
  color: "bg-emerald-100",
};
